'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Phone, Menu, X, PaintBucket } from 'lucide-react';

export function Header() {
  const [open, setOpen] = useState(false);
  const links = [{ name: 'Services', href: '/#services' }, { name: 'About Brent', href: '/#about' }, { name: 'Work quality', href: '/#portfolio' }, { name: 'Contact', href: '/#contact' }];
  return <header className="fixed top-0 left-0 right-0 z-50 glass"><nav className="container mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between h-16 sm:h-20"><Link href="/" className="flex items-center gap-3"><div className="relative w-10 h-10 bg-accent flex items-center justify-center"><span className="absolute -right-1 -top-1 w-3 h-3 bg-white" /><PaintBucket className="w-5 h-5 text-black" /></div><div><div className="font-extrabold tracking-tight">STEEL CITY</div><div className="text-[10px] font-semibold tracking-[0.18em] text-zinc-400">PAINTING & HANDYMAN</div></div></Link><div className="hidden lg:flex items-center gap-7">{links.map((link) => <Link key={link.name} href={link.href} className="text-sm font-semibold text-zinc-200 hover:text-accent transition-colors">{link.name}</Link>)}</div><div className="flex items-center gap-3"><a href="tel:2897752020" className="hidden sm:flex items-center gap-2 px-4 py-2.5 bg-accent text-black text-sm font-bold hover:bg-white transition-colors"><Phone className="w-4 h-4" /> Call / text Brent</a><button onClick={() => setOpen(!open)} className="lg:hidden p-2 text-white" aria-label="Toggle menu">{open ? <X /> : <Menu />}</button></div></div>{open && <div className="lg:hidden py-4 border-t border-border"><div className="flex flex-col gap-1">{links.map((link) => <Link key={link.name} href={link.href} onClick={() => setOpen(false)} className="py-3 text-sm font-semibold text-zinc-200">{link.name}</Link>)}<a href="tel:2897752020" className="mt-2 flex items-center justify-center gap-2 py-3 bg-accent text-black font-bold"><Phone className="w-4 h-4" />(289) 775-2020</a></div></div>}</nav></header>;
}
